# netlify.toml
[build]
  publish = "."
  functions = "netlify/functions"
# Adicione este plugin para resolver o problema de dependências
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  command = "npm run dev"
  port = 8888
  publish = "."
